# Generated by Django 2.1.15 on 2020-12-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('amount', models.FloatField(db_index=True)),
                ('product_name', models.CharField(db_index=True, max_length=40)),
                ('created_time', models.DateTimeField(db_index=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(db_index=True)),
                ('product_name', models.CharField(db_index=True, max_length=40)),
                ('created_time', models.DateTimeField(db_index=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'sale',
                'verbose_name_plural': 'sales',
            },
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral', models.CharField(max_length=50)),
                ('visitors', models.PositiveIntegerField()),
                ('rate', models.FloatField()),
                ('rate_type', models.SmallIntegerField(choices=[(1, 'up'), (2, 'down')])),
                ('created_time', models.DateTimeField(db_index=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'traffic',
                'verbose_name_plural': 'traffics',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('visitors', models.PositiveIntegerField()),
                ('unique_users', models.PositiveIntegerField()),
                ('bounce_rate', models.FloatField()),
                ('bounce_rate_type', models.SmallIntegerField(choices=[(1, 'up'), (2, 'down')])),
                ('created_time', models.DateTimeField(db_index=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'visit',
                'verbose_name_plural': 'visits',
            },
        ),
    ]
